name = "conditional-simulation"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ConditionalSimulation", "CoRefinementConvergence", "ICTACCorrespondence", "ExtractionPossibility", "Learnability"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[lean_lib]]
name = "ConditionalSimulation"

[[lean_lib]]
name = "CoRefinementConvergence"

[[lean_lib]]
name = "ICTACCorrespondence"

[[lean_lib]]
name = "ExtractionPossibility"

[[lean_lib]]
name = "Learnability"
